version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    restart: always
    command: gunicorn --chdir /usr/src/app wlsite.wsgi --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./dockerdata/media:/usr/src/app/mediafiles
    depends_on:
      - db

  db:
    image: mariadb:10.7
    restart: always
    volumes:
      - ./dockerdata/db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: web
      MYSQL_USER: web
    env_file:
      - .env

  nginx:
    build: nginx
    restart: always
    expose:
      - 80
    #ports:
    #  - 8000:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
      #- ./dockerdata/media:/usr/src/app/mediafiles
    depends_on:
      - web
    networks:
      - default
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.SERVICENAME.rule=Host(`DOMAIN.it`)
      - traefik.http.routers.SERVICENAME.tls=true

volumes:
  static_volume:

networks:
  web:
    external: true
