FROM python:3-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN adduser -S appuser

RUN apk add --no-cache mariadb-dev build-base libffi-dev jpeg-dev zlib-dev

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./docker_entrypoint.sh /docker_entrypoint.sh
RUN chmod +x /docker_entrypoint.sh

COPY ./wlsite /usr/src/app
RUN mkdir /usr/src/app/staticfiles
RUN mkdir /usr/src/app/mediafiles

RUN chown -R appuser /usr/src/app

USER appuser
ENTRYPOINT ["/docker_entrypoint.sh"]
