version: "3.8"

services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./dockerdata/media:/usr/src/app/mediafiles
      - ./wlsite:/usr/src/app
    depends_on:
      - db
    environment:
      DEBUG: 1

  db:
    image: mariadb:10.7
    restart: always
    volumes:
      - ./dockerdata/db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: web
      MYSQL_USER: web
    env_file:
      - ./.env
