# Generated by Django 3.2.9 on 2022-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_activity_title_activity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('vat', models.CharField(max_length=250)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
