# Generated by Django 3.2.9 on 2022-03-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resourcelink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
