# Generated by Django 3.2.9 on 2022-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220308_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(related_name='dependencies_task', to='api.Task')),
            ],
        ),
    ]
