# Generated by Django 3.2.9 on 2022-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='dependencies_task', to='api.Task'),
        ),
    ]
