# Generated by Django 3.2.9 on 2022-03-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_task_dependencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependencies_task', to='api.Task'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_item', to='api.task')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='workers',
            field=models.ManyToManyField(to='api.Worker'),
        ),
        migrations.AddField(
            model_name='team',
            name='workers',
            field=models.ManyToManyField(to='api.Worker'),
        ),
    ]
