# Generated by Django 3.2.9 on 2022-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_priority_statust_statusti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('customer', models.ManyToManyField(to='api.Customer')),
            ],
        ),
    ]
