# Generated by Django 3.2.9 on 2022-03-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusT',
        ),
        migrations.DeleteModel(
            name='StatusTi',
        ),
    ]
