# Generated by Django 3.2.9 on 2022-03-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220308_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.ManyToManyField(to='api.Activity')),
            ],
        ),
    ]
